<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bo.rt.biz.scm.purchaseorder</groupId>
        <artifactId>scm-purchaseorder-next-service</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>purchaseorder-next-test</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>purchaseorder-next-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>purchaseorder-next-application</artifactId>
        </dependency>
    </dependencies>
</project>
