<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bo.rt.framework</groupId>
        <artifactId>bo-rt-framework-parent</artifactId>
        <version>0.9-release</version>
    </parent>

    <groupId>com.bo.rt.biz.scm.purchaseorder</groupId>
    <artifactId>scm-purchaseorder-next-service</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>purchaseorder-next-api</module>
        <module>purchaseorder-next-domain</module>
        <module>purchaseorder-next-application</module>
        <module>purchaseorder-next-infrastructure</module>
        <module>purchaseorder-next-interfaces</module>
        <module>purchaseorder-next-starter</module>
        <module>purchaseorder-next-test</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>purchaseorder-next-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>purchaseorder-next-domain</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>purchaseorder-next-application</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>purchaseorder-next-infrastructure</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>purchaseorder-next-interfaces</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
